### ISSUE TITLE
Thank you page content should depend on query string

### ISSUE THREAD

**Issue by jacobhilton** [centre-for-effective-altruism/givingwhatwecan-org-static#24]
https://www.givingwhatwecan.org/thank-you/ has been imported from https://www.givingwhatwecan.org/node/144/edit but as the PHP code has been stripped, the content no longer depends on the query string and instead repeats itself. The three pages https://www.givingwhatwecan.org/thank-you?f=signup , https://www.givingwhatwecan.org/thank-you?f=trygiving and https://www.givingwhatwecan.org/thank-you?f=pledge should all be different.

**Comment by colophonemes** [comment]
Fixed in Contentful, will be updated on next site rebuild
